import { execFile } from "node:child_process";
import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { promisify } from "node:util";
import { runStreamingCommand } from "./command.mjs";
import { CONFIG_DIR } from "./constants.mjs";

const execFileAsync = promisify(execFile);

/** @param {string} source */
function hasPackageCodexInstall(source) {
  return source.split(/\r?\n/).some(
    (line) =>
      /^\s*RUN\s+npm\s+install\b/.test(line) &&
      line.includes("@openai/codex"),
  );
}

/**
 * Remove the Codex install block from the package's pre-overlay Dockerfile.
 * The actual install is performed by the temporary derived layer below.
 * @param {string} source
 */
function deferPackageCodexInstall(source) {
  const output = [];
  let skipping = false;
  for (const line of source.split(/\r?\n/)) {
    if (
      !skipping &&
      /^\s*RUN\s+npm\s+install\b/.test(line) &&
      line.includes("@openai/codex")
    ) {
      output.push(
        "# Codex installation is applied by sandcastle-for-agent's temporary layer.",
      );
      skipping = line.trimEnd().endsWith("\\");
      continue;
    }
    if (skipping) {
      skipping = line.trimEnd().endsWith("\\");
      continue;
    }
    output.push(line);
  }
  return output.join("\n");
}

/**
 * @param {string} buildContext
 * @param {string} temporaryBuildDir
 * @returns {Promise<string | undefined>}
 */
async function prepareBaseDockerfile(buildContext, temporaryBuildDir) {
  let source;
  try {
    source = await readFile(join(buildContext, "Dockerfile"), "utf8");
  } catch {
    return undefined;
  }
  if (!hasPackageCodexInstall(source)) return undefined;
  const path = join(temporaryBuildDir, "Base.Dockerfile");
  await writeFile(path, deferPackageCodexInstall(source), "utf8");
  return path;
}

/**
 * @param {object} options
 * @param {string} options.cwd
 * @param {import("./config.mjs").ProjectConfig} options.config
 * @param {(file: string, args: string[], options: {cwd: string}) => Promise<unknown>} [options.exec]
 */
export async function buildImage({ cwd, config, exec = runStreamingCommand }) {
  const uid = process.getuid?.() ?? 1000;
  const gid = process.getgid?.() ?? 1000;
  const buildContext = join(cwd, CONFIG_DIR);
  const intermediateTag = `sandcastle-for-agent-base-${process.pid}-${Date.now()}`;
  const temporaryBuildDir = await mkdtemp(join(tmpdir(), "sandcastle-for-agent-build-"));

  try {
    const baseDockerfile = await prepareBaseDockerfile(
      buildContext,
      temporaryBuildDir,
    );

    // Keep the Dockerfile generated by upstream Sandcastle as the base image.
    const baseBuildArgs = [
      "build",
      "-t",
      intermediateTag,
      "--build-arg",
      `AGENT_UID=${uid}`,
      "--build-arg",
      `AGENT_GID=${gid}`,
    ];
    if (baseDockerfile) baseBuildArgs.push("-f", baseDockerfile);
    baseBuildArgs.push(buildContext);
    await exec(
      "docker",
      baseBuildArgs,
      { cwd },
    );

    const temporaryDockerfile = join(temporaryBuildDir, "Dockerfile");
    await writeFile(
      temporaryDockerfile,
      `FROM ${intermediateTag}

USER root

ARG AGENT_UID=1000
ARG AGENT_GID=1000

RUN install -d -o $AGENT_UID -g $AGENT_GID /home/agent/.codex \\
  && codex_root="$(npm root -g)/@openai/codex" \\
  && if [ ! -f "$codex_root/package.json" ]; then npm install -g @openai/codex; fi \\
  && codex_version="$(node -p 'require(process.argv[1]).version' "$codex_root/package.json")" \\
  && case "$(dpkg --print-architecture)" in \\
       arm64) codex_platform="linux-arm64" ;; \\
       amd64) codex_platform="linux-x64" ;; \\
       *) echo "Unsupported Docker architecture: $(dpkg --print-architecture)" >&2; exit 1 ;; \\
     esac \\
  && npm install --prefix "$codex_root" --no-save --package-lock=false \\
       "@openai/codex-$codex_platform@npm:@openai/codex@$codex_version-$codex_platform" \\
  && codex --version

USER $AGENT_UID:$AGENT_GID
`,
      "utf8",
    );

    await exec(
      "docker",
      [
        "build",
        "-t",
        config.imageName,
        "--build-arg",
        `AGENT_UID=${uid}`,
        "--build-arg",
        `AGENT_GID=${gid}`,
        "-f",
        temporaryDockerfile,
        buildContext,
      ],
      { cwd },
    );
  } finally {
    await rm(temporaryBuildDir, { recursive: true, force: true });
    await exec("docker", ["image", "rm", intermediateTag], { cwd }).catch(() => {});
  }
}

/** @param {object} options @param {string} options.cwd @param {import("./config.mjs").ProjectConfig} options.config */
export async function assertImageExists({ cwd, config }) {
  try {
    await execFileAsync("docker", ["image", "inspect", config.imageName], { cwd });
  } catch {
    throw new Error(
      `Docker image '${config.imageName}' is missing. Run 'sandcastle-for-agent build'.`,
    );
  }
}
